GOOGLE_CLIENT_ID: "945179212623-ka1k0gmsucs4r73lq8o8om5agdsuc42a.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET: "R7pCPsAwUj5Ao3CwOrcLJrbX"
MAPBOX_TOKEN: "pk.eyJ1IjoicHJvZ2V0dG9hcyIsImEiOiJjamtpaTU0MWgwb2h1M3BwMDR5YjB6bzlsIn0.tXb1qhAs4QoO4-m2X2ZETA"
MAPBOX_TOKEN_GENERATOR: "sk.eyJ1IjoicHJvZ2V0dG9hcyIsImEiOiJjamwxOWFlMm8weDhtM2tuMmZseDA4N3NyIn0.z3oRDyire5XgZ6AzctZY9A"
MAPBOX_USERNAME: "progettoas"
